[project]
name = "fmnist-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "notebook>=7.5.1",
    "numpy>=2.4.1",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
